`timescale 1ns / 1ps
// tb_corpus_perf.v  --  GENERATED by analysis/gen_corpus_tb.py. Do not edit by hand.
// Streams every corpus line through tokenizer_axi_lite at 1 byte/clock and records the
// deterministic fabric cycle count + token IDs to C:/Users/talsh/.Xilinx/projects/uart/analysis/results/fpga_results.csv.

module tb_corpus_perf;
    localparam integer N      = 66;
    localparam integer TOTAL  = 16099;
    localparam integer TOKEN_W = 16;

    reg clk = 1'b0;  always #5 clk = ~clk;          // 100 MHz (10 ns)
    reg aresetn = 1'b0;

    // corpus storage + per-line index
    reg  [7:0] cbytes [0:TOTAL-1];
    integer    line_start [0:N-1];
    integer    line_len   [0:N-1];

    // AXI4-Stream (input bytes / output tokens)
    reg  [7:0]         s_tdata;  reg s_tvalid; wire s_tready; reg s_tlast;
    wire [TOKEN_W-1:0] m_tdata;  wire m_tvalid; reg m_tready;  wire m_tlast;
    wire s_fire = s_tvalid && s_tready;
    wire m_fire = m_tvalid && m_tready;

    // AXI-Lite tied off (this TB uses only the stream path)
    wire s_axi_awready, s_axi_wready, s_axi_bvalid, s_axi_arready, s_axi_rvalid;
    wire [1:0] s_axi_bresp, s_axi_rresp;
    wire [31:0] s_axi_rdata;

    tokenizer_axi_lite #(.TOKEN_W(TOKEN_W)) uut (
        .s_axi_aclk(clk), .s_axi_aresetn(aresetn),
        .s_axi_awaddr(4'd0), .s_axi_awvalid(1'b0), .s_axi_awready(s_axi_awready),
        .s_axi_wdata(32'd0), .s_axi_wstrb(4'd0), .s_axi_wvalid(1'b0), .s_axi_wready(s_axi_wready),
        .s_axi_bresp(s_axi_bresp), .s_axi_bvalid(s_axi_bvalid), .s_axi_bready(1'b0),
        .s_axi_araddr(4'd0), .s_axi_arvalid(1'b0), .s_axi_arready(s_axi_arready),
        .s_axi_rdata(s_axi_rdata), .s_axi_rresp(s_axi_rresp), .s_axi_rvalid(s_axi_rvalid), .s_axi_rready(1'b0),
        .s_axis_tdata(s_tdata), .s_axis_tvalid(s_tvalid), .s_axis_tready(s_tready), .s_axis_tlast(s_tlast),
        .m_axis_tdata(m_tdata), .m_axis_tvalid(m_tvalid), .m_axis_tready(m_tready), .m_axis_tlast(m_tlast)
    );

    // free-running cycle counter (the measurement clock)
    integer cyc = 0;
    always @(posedge clk) cyc <= cyc + 1;

    // per-line capture
    integer ntok;
    reg [TOKEN_W-1:0] toks [0:1023];
    integer t_first, t_last, t_indone;
    reg first_seen, last_seen;
    reg clr;

    always @(posedge clk) begin
        if (clr) begin
            ntok <= 0; first_seen <= 1'b0; last_seen <= 1'b0;
            t_first <= 0; t_last <= 0; t_indone <= 0;
        end else begin
            if (s_fire && !first_seen) begin t_first <= cyc; first_seen <= 1'b1; end
            if (s_fire && s_tlast)     t_indone <= cyc;       // last input byte accepted
            if (m_fire) begin
                toks[ntok] <= m_tdata; ntok <= ntok + 1;
                if (m_tlast) begin t_last <= cyc; last_seen <= 1'b1; end
            end
        end
    end

    // stream one line's bytes + a trailing boundary (0x20) carrying TLAST, driving on the
    // negedge so values are stable when the DUT samples at the posedge (holds on backpressure).
    task stream_line(input integer start, input integer len);
        integer k;
        begin
            for (k = 0; k < len; k = k + 1) begin
                @(negedge clk); s_tdata = cbytes[start + k]; s_tvalid = 1'b1; s_tlast = 1'b0;
                @(posedge clk); while (!s_tready) begin @(negedge clk); @(posedge clk); end
            end
            @(negedge clk); s_tdata = 8'h20; s_tvalid = 1'b1; s_tlast = 1'b1;   // boundary flush
            @(posedge clk); while (!s_tready) begin @(negedge clk); @(posedge clk); end
            @(negedge clk); s_tvalid = 1'b0; s_tlast = 1'b0;
        end
    endtask

    integer fd, i, j, k;
    initial begin
        s_tdata = 8'd0; s_tvalid = 1'b0; s_tlast = 1'b0; m_tready = 1'b1; clr = 1'b0;
        $readmemh("C:/Users/talsh/.Xilinx/projects/uart/analysis/corpus_bytes.mem", cbytes);
        line_start[0] = 0; line_len[0] = 16;
        line_start[1] = 16; line_len[1] = 19;
        line_start[2] = 35; line_len[2] = 14;
        line_start[3] = 49; line_len[3] = 16;
        line_start[4] = 65; line_len[4] = 26;
        line_start[5] = 91; line_len[5] = 19;
        line_start[6] = 110; line_len[6] = 44;
        line_start[7] = 154; line_len[7] = 94;
        line_start[8] = 248; line_len[8] = 62;
        line_start[9] = 310; line_len[9] = 86;
        line_start[10] = 396; line_len[10] = 102;
        line_start[11] = 498; line_len[11] = 98;
        line_start[12] = 596; line_len[12] = 317;
        line_start[13] = 913; line_len[13] = 314;
        line_start[14] = 1227; line_len[14] = 255;
        line_start[15] = 1482; line_len[15] = 232;
        line_start[16] = 1714; line_len[16] = 259;
        line_start[17] = 1973; line_len[17] = 251;
        line_start[18] = 2224; line_len[18] = 1125;
        line_start[19] = 3349; line_len[19] = 777;
        line_start[20] = 4126; line_len[20] = 1007;
        line_start[21] = 5133; line_len[21] = 13;
        line_start[22] = 5146; line_len[22] = 14;
        line_start[23] = 5160; line_len[23] = 16;
        line_start[24] = 5176; line_len[24] = 15;
        line_start[25] = 5191; line_len[25] = 14;
        line_start[26] = 5205; line_len[26] = 12;
        line_start[27] = 5217; line_len[27] = 63;
        line_start[28] = 5280; line_len[28] = 68;
        line_start[29] = 5348; line_len[29] = 53;
        line_start[30] = 5401; line_len[30] = 64;
        line_start[31] = 5465; line_len[31] = 58;
        line_start[32] = 5523; line_len[32] = 66;
        line_start[33] = 5589; line_len[33] = 231;
        line_start[34] = 5820; line_len[34] = 234;
        line_start[35] = 6054; line_len[35] = 257;
        line_start[36] = 6311; line_len[36] = 230;
        line_start[37] = 6541; line_len[37] = 234;
        line_start[38] = 6775; line_len[38] = 254;
        line_start[39] = 7029; line_len[39] = 488;
        line_start[40] = 7517; line_len[40] = 421;
        line_start[41] = 7938; line_len[41] = 429;
        line_start[42] = 8367; line_len[42] = 799;
        line_start[43] = 9166; line_len[43] = 651;
        line_start[44] = 9817; line_len[44] = 767;
        line_start[45] = 10584; line_len[45] = 16;
        line_start[46] = 10600; line_len[46] = 10;
        line_start[47] = 10610; line_len[47] = 15;
        line_start[48] = 10625; line_len[48] = 18;
        line_start[49] = 10643; line_len[49] = 15;
        line_start[50] = 10658; line_len[50] = 13;
        line_start[51] = 10671; line_len[51] = 69;
        line_start[52] = 10740; line_len[52] = 64;
        line_start[53] = 10804; line_len[53] = 73;
        line_start[54] = 10877; line_len[54] = 74;
        line_start[55] = 10951; line_len[55] = 69;
        line_start[56] = 11020; line_len[56] = 70;
        line_start[57] = 11090; line_len[57] = 301;
        line_start[58] = 11391; line_len[58] = 405;
        line_start[59] = 11796; line_len[59] = 451;
        line_start[60] = 12247; line_len[60] = 440;
        line_start[61] = 12687; line_len[61] = 350;
        line_start[62] = 13037; line_len[62] = 369;
        line_start[63] = 13406; line_len[63] = 956;
        line_start[64] = 14362; line_len[64] = 806;
        line_start[65] = 15168; line_len[65] = 931;

        fd = $fopen("C:/Users/talsh/.Xilinx/projects/uart/analysis/results/fpga_results.csv", "w");
        $fwrite(fd, "idx,chars,tokens,fabric_cycles,input_cycles,fpga_ids\n");

        aresetn = 1'b0; clr = 1'b1; repeat (10) @(posedge clk);
        aresetn = 1'b1; clr = 1'b0; repeat (5) @(posedge clk);

        for (i = 0; i < N; i = i + 1) begin
            clr = 1'b1; @(posedge clk); clr = 1'b0;       // reset collector for this line
            stream_line(line_start[i], line_len[i]);
            j = 0; while (!last_seen && j < 500000) begin @(posedge clk); j = j + 1; end
            $fwrite(fd, "%0d,%0d,%0d,%0d,%0d,",
                    i, line_len[i], ntok,
                    (last_seen ? (t_last  - t_first + 1) : 0),
                    (last_seen ? (t_indone - t_first + 1) : 0));
            for (k = 0; k < ntok; k = k + 1) $fwrite(fd, "%0d ", toks[k]);
            $fwrite(fd, "\n");
            if (!last_seen) $display("WARN line %0d: no TLAST (timeout)", i);
            repeat (20) @(posedge clk);                   // let the pipeline settle
        end

        $fclose(fd);
        $display("tb_corpus_perf: wrote %0d lines to C:/Users/talsh/.Xilinx/projects/uart/analysis/results/fpga_results.csv", N);
        $finish;
    end

    initial begin
        #2_000_000_000;                                   // 2 ms hard watchdog
        $display("ERROR: tb_corpus_perf TIMED OUT");
        $fclose(fd);
        $finish;
    end
endmodule
