#!/usr/bin/env python3
"""
gen_corpus_tb.py  --  generate the FPGA measurement testbench from corpus.txt.

The FPGA "core" (fabric) latency is a CYCLE COUNT, measured in simulation by streaming
each corpus line through the real tokenizer_axi_lite RTL at 1 byte/clock (the s_axis / DMA
path) and timing from the first input byte accepted to the last token emitted. This is the
deterministic fabric number -- no AXI-Lite cadence, no DMA setup, no cache overhead.

This script reads corpus.txt and emits:
  * corpus_bytes.mem  -- every corpus byte, one hex value per line ($readmemh source)
  * tb_corpus_perf.v  -- the testbench (written into uart.srcs/sim_1/new/), which:
       - loops over all N corpus lines,
       - streams each line's bytes + a trailing boundary (so the last word flushes -> TLAST),
       - records, per line: char count, token count, fabric_cycles (first byte->last token),
         input_cycles (first byte->last byte accepted), and the emitted token IDs,
       - $fwrites one CSV row per line to results/fpga_results.csv.

Paths are baked in as ABSOLUTE (forward-slash) to dodge the recurring xsim ".mem not found"
problem. Re-run this script if you move the project. After generating: in Vivado add
tb_corpus_perf.v as a simulation source, set it as the sim top, and run behavioral simulation
(the 9 trie .mem files load as usual). Then results/fpga_results.csv is ready for the compare/plot step.
"""
import os

HERE    = os.path.dirname(os.path.abspath(__file__))
CORPUS  = os.path.join(HERE, "corpus.txt")
MEM_OUT = os.path.join(HERE, "corpus_bytes.mem")
TB_OUT  = os.path.normpath(os.path.join(HERE, "..", "uart.srcs", "sim_1", "new", "tb_corpus_perf.v"))
CSV_OUT = os.path.join(HERE, "results", "fpga_results.csv")


def fwd(p):
    return os.path.abspath(p).replace("\\", "/")


def main():
    with open(CORPUS, encoding="utf-8") as f:
        lines = [ln.rstrip("\n") for ln in f if ln.strip()]

    data, starts, lens = bytearray(), [], []
    for ln in lines:
        b = ln.encode("ascii")          # corpus is ASCII by construction
        starts.append(len(data))
        lens.append(len(b))
        data.extend(b)
    N, TOTAL = len(lines), len(data)

    os.makedirs(os.path.dirname(CSV_OUT), exist_ok=True)
    with open(MEM_OUT, "w", encoding="ascii") as f:
        f.write("\n".join(f"{x:02x}" for x in data) + "\n")

    inits = "\n".join(
        f"        line_start[{i}] = {starts[i]}; line_len[{i}] = {lens[i]};"
        for i in range(N)
    )

    tb = f"""`timescale 1ns / 1ps
// tb_corpus_perf.v  --  GENERATED by analysis/gen_corpus_tb.py. Do not edit by hand.
// Streams every corpus line through tokenizer_axi_lite at 1 byte/clock and records the
// deterministic fabric cycle count + token IDs to {fwd(CSV_OUT)}.

module tb_corpus_perf;
    localparam integer N      = {N};
    localparam integer TOTAL  = {TOTAL};
    localparam integer TOKEN_W = 16;

    reg clk = 1'b0;  always #5 clk = ~clk;          // 100 MHz (10 ns)
    reg aresetn = 1'b0;

    // corpus storage + per-line index
    reg  [7:0] cbytes [0:TOTAL-1];
    integer    line_start [0:N-1];
    integer    line_len   [0:N-1];

    // AXI4-Stream (input bytes / output tokens)
    reg  [7:0]         s_tdata;  reg s_tvalid; wire s_tready; reg s_tlast;
    wire [TOKEN_W-1:0] m_tdata;  wire m_tvalid; reg m_tready;  wire m_tlast;
    wire s_fire = s_tvalid && s_tready;
    wire m_fire = m_tvalid && m_tready;

    // AXI-Lite tied off (this TB uses only the stream path)
    wire s_axi_awready, s_axi_wready, s_axi_bvalid, s_axi_arready, s_axi_rvalid;
    wire [1:0] s_axi_bresp, s_axi_rresp;
    wire [31:0] s_axi_rdata;

    tokenizer_axi_lite #(.TOKEN_W(TOKEN_W)) uut (
        .s_axi_aclk(clk), .s_axi_aresetn(aresetn),
        .s_axi_awaddr(4'd0), .s_axi_awvalid(1'b0), .s_axi_awready(s_axi_awready),
        .s_axi_wdata(32'd0), .s_axi_wstrb(4'd0), .s_axi_wvalid(1'b0), .s_axi_wready(s_axi_wready),
        .s_axi_bresp(s_axi_bresp), .s_axi_bvalid(s_axi_bvalid), .s_axi_bready(1'b0),
        .s_axi_araddr(4'd0), .s_axi_arvalid(1'b0), .s_axi_arready(s_axi_arready),
        .s_axi_rdata(s_axi_rdata), .s_axi_rresp(s_axi_rresp), .s_axi_rvalid(s_axi_rvalid), .s_axi_rready(1'b0),
        .s_axis_tdata(s_tdata), .s_axis_tvalid(s_tvalid), .s_axis_tready(s_tready), .s_axis_tlast(s_tlast),
        .m_axis_tdata(m_tdata), .m_axis_tvalid(m_tvalid), .m_axis_tready(m_tready), .m_axis_tlast(m_tlast)
    );

    // free-running cycle counter (the measurement clock)
    integer cyc = 0;
    always @(posedge clk) cyc <= cyc + 1;

    // per-line capture
    integer ntok;
    reg [TOKEN_W-1:0] toks [0:1023];
    integer t_first, t_last, t_indone;
    reg first_seen, last_seen;
    reg clr;

    always @(posedge clk) begin
        if (clr) begin
            ntok <= 0; first_seen <= 1'b0; last_seen <= 1'b0;
            t_first <= 0; t_last <= 0; t_indone <= 0;
        end else begin
            if (s_fire && !first_seen) begin t_first <= cyc; first_seen <= 1'b1; end
            if (s_fire && s_tlast)     t_indone <= cyc;       // last input byte accepted
            if (m_fire) begin
                toks[ntok] <= m_tdata; ntok <= ntok + 1;
                if (m_tlast) begin t_last <= cyc; last_seen <= 1'b1; end
            end
        end
    end

    // stream one line's bytes + a trailing boundary (0x20) carrying TLAST, driving on the
    // negedge so values are stable when the DUT samples at the posedge (holds on backpressure).
    task stream_line(input integer start, input integer len);
        integer k;
        begin
            for (k = 0; k < len; k = k + 1) begin
                @(negedge clk); s_tdata = cbytes[start + k]; s_tvalid = 1'b1; s_tlast = 1'b0;
                @(posedge clk); while (!s_tready) begin @(negedge clk); @(posedge clk); end
            end
            @(negedge clk); s_tdata = 8'h20; s_tvalid = 1'b1; s_tlast = 1'b1;   // boundary flush
            @(posedge clk); while (!s_tready) begin @(negedge clk); @(posedge clk); end
            @(negedge clk); s_tvalid = 1'b0; s_tlast = 1'b0;
        end
    endtask

    integer fd, i, j, k;
    initial begin
        s_tdata = 8'd0; s_tvalid = 1'b0; s_tlast = 1'b0; m_tready = 1'b1; clr = 1'b0;
        $readmemh("{fwd(MEM_OUT)}", cbytes);
{inits}

        fd = $fopen("{fwd(CSV_OUT)}", "w");
        $fwrite(fd, "idx,chars,tokens,fabric_cycles,input_cycles,fpga_ids\\n");

        aresetn = 1'b0; clr = 1'b1; repeat (10) @(posedge clk);
        aresetn = 1'b1; clr = 1'b0; repeat (5) @(posedge clk);

        for (i = 0; i < N; i = i + 1) begin
            clr = 1'b1; @(posedge clk); clr = 1'b0;       // reset collector for this line
            stream_line(line_start[i], line_len[i]);
            j = 0; while (!last_seen && j < 500000) begin @(posedge clk); j = j + 1; end
            $fwrite(fd, "%0d,%0d,%0d,%0d,%0d,",
                    i, line_len[i], ntok,
                    (last_seen ? (t_last  - t_first + 1) : 0),
                    (last_seen ? (t_indone - t_first + 1) : 0));
            for (k = 0; k < ntok; k = k + 1) $fwrite(fd, "%0d ", toks[k]);
            $fwrite(fd, "\\n");
            if (!last_seen) $display("WARN line %0d: no TLAST (timeout)", i);
            repeat (20) @(posedge clk);                   // let the pipeline settle
        end

        $fclose(fd);
        $display("tb_corpus_perf: wrote %0d lines to {fwd(CSV_OUT)}", N);
        $finish;
    end

    initial begin
        #2_000_000_000;                                   // 2 ms hard watchdog
        $display("ERROR: tb_corpus_perf TIMED OUT");
        $fclose(fd);
        $finish;
    end
endmodule
"""
    os.makedirs(os.path.dirname(TB_OUT), exist_ok=True)
    with open(TB_OUT, "w", encoding="ascii") as f:
        f.write(tb)

    print(f"Corpus: {N} lines, {TOTAL} bytes")
    print(f"Wrote   {MEM_OUT}")
    print(f"Wrote   {TB_OUT}")
    print(f"TB will emit -> {CSV_OUT}")
    print("\nNext: in Vivado, add tb_corpus_perf.v as a simulation source, set it as sim top,")
    print("and run behavioral simulation. Then results/fpga_results.csv is ready.")


if __name__ == "__main__":
    main()
